### ISSUE TITLE
Add wheels support

### ISSUE THREAD

**Issue by Natim** [novafloss/django-generic-filters#1]
http://pythonwheels.com/

**Comment by tmartinfr** [comment]
Wheel packages can be created using: `python setup.py bdist_wheel`.
They are also pushed to localshop for each new releases.

**Comment by aRkadeFR** [comment]
They also can be universal to use the same wheel between py2 and py3 :)

**Comment by Natim** [comment]
The way we do it usually is by configuring setup.cfg like that: https://github.com/Kinto/kinto-changes/blob/master/setup.cfg

**Comment by tmartinfr** [comment]
@Natim It should probably depends on general guidelines for every Python novafloss projects. Would you agree to close this old issue ?

**Comment by tmartinfr** [comment]
@Natim I close, re-open it if necessary !

**Comment by Natim** [comment]
I didn't get that you wanted to close it without actually fixing it, can I file a pull-request for it?

**Comment by tmartinfr** [comment]
@Natim Because it's a very old issue and nobody plans to work on it. But of course you're welcome to submit a PR !

**Comment by Natim** [comment]
Ok I just did then :)

**Comment by tmartinfr** [comment]
@Natim Thanks I'm looking at it

**Comment by tmartinfr** [comment]
@Natim Looks good, but I guess we have to wait for #40 and #49 before publishing py3 wheels.

**Comment by Natim** [comment]
We won't publish py3 wheels we are pushing an universal one.

**Comment by tmartinfr** [comment]
@Natim I don't understand why we would want to create universal wheel file while the package is not currently universal ? If I refer to http://pythonwheels.com/ :

> Note: If your project is python 2 and 3 compatible you can create a universal wheel distribution.

Maybe we could remove the `[bdist_wheel]` section in the PR ? If so, it would be ok for me to merge. Then we could add it back after #49.

**Comment by Natim** [comment]
I believe it depends if you plan on merging #49 before the next release or not...

**Comment by tmartinfr** [comment]
@Natim I have to test it. Meanwhile your PR can stay open and I'll merge it when appropriate :-)
