### ISSUE TITLE
Milestones in Github

### ISSUE THREAD

**Issue by benoitbryon** [novafloss/django-generic-filters#26]
Unless otherwise specified, I will setup the following milestones to manage issues in the bugtracker:
- have a X.X (example: 0.9) milestone for features we merge in master. So that we can get the list of tickets for each release.
- have a "soon" milestone, where we put tickets with either high priority or simple changes: tickets that are candidates for the next milestone. As an example features/bugs that are must-have.
- have a "later" milestone, where we put tickets with lower priority. As an example features that are nice-to-have or tickets that are too big for a near future.
- have a "maybe, one day" milestone, where we put ideas we'd like to implement, but that we do not plan to implement soon. As an example features that involve really big changes, or significant API changes... This milestone would participate to vision, a.k.a. the long term roadmap.

I use this scheme in several projects, such as:
- https://github.com/diecutter/diecutter/issues/milestones
- https://github.com/benoitbryon/django-downloadview/issues/milestones
- https://github.com/python-hospital/hospital/issues/milestones

... and I like it ;)

CHANGELOG and README also mention the "roadmap". Example: https://github.com/diecutter/diecutter/blob/9d9066a17dde6cd42cea4301ba576ed669ef7ed1/README.rst (end of file) and https://github.com/diecutter/diecutter/blob/9d9066a17dde6cd42cea4301ba576ed669ef7ed1/CHANGELOG#L197

I can publish an article on this topic on our Novapost blog, then reference this article in the CONTRIBUTING file.

**Comment by tmartinfr** [comment]
@benoitbryon Maybe we should have generic guidelines like this for every novafloss repo (maybe it already exists somewhere ?

**Comment by tmartinfr** [comment]
@benoitbryon I close, re-open it if necessary !
