### ISSUE TITLE
Documentation? purpose of the QueryFormMixin

### ISSUE THREAD

**Issue by techdragon** [novafloss/django-generic-filters#43]
If `queryformmixin` only exists to attach a hidden text input field on the form, which was quite confusing at first, why is it setup like this? 

I have to not use it in order to do any queries unless i want to un-hide the query input on the client using javascript. It just seem so contradictory. Is there some explanation why its setup like this? Otherwise I may write a pull request to clean it up.

**Comment by tmartinfr** [comment]
@techdragon Not sure to understand "I have to not use it in order to do any queries". Could you reformulate ?

**Comment by tmartinfr** [comment]
@techdragon I close, re-open it if necessary !
